name: Deploy to Vercel

on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20.1.0
      with:
        vercel_token: ${{ secrets.VERCEL_TOKEN }}
        vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
